server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /admin/ {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        try_files $uri $uri/ $uri.html /admin/index.html;
    }

    location / {
        rewrite ^(.+)/index$           $1/ permanent;
        rewrite ^(/.+(?<!index))\.html$ $1  permanent;
        try_files $uri $uri/ $uri.html /index.html;
    }

    location ~ /\. {
        deny all;
    }
}
